-- Replace the three starter records with the 20 schemes from the legacy catalog.
-- Stable UUIDs keep links from the home page and scheme details repeatable.
delete from public.schemes
where id in (
  'd12875a4-f5b2-4f1a-8a18-b1a90b46e80c',
  '20c1bb6a-017d-4f0d-a16a-42fdf4a79d12'
);

insert into public.schemes (
  id, scheme_name, category, level, ministry, description, benefits,
  gender, occupation, disability_required, official_url, is_published
)
values
  ('bceb0c4b-501c-45e3-a978-5f1c398852bc', 'AICTE - Pragati Scholarship Scheme For Girl Students (Technical Degree)', 'Education', 'Central', 'All India Council for Technical Education', 'Scholarship support for eligible girl students pursuing a technical degree in an AICTE-approved institution. See the official portal for current criteria and application dates.', 'Financial scholarship support as set out in the current scheme guidelines.', 'Female', null, false, 'https://scholarships.gov.in/All-Scholarships', true),
  ('f82caad8-24e7-45ac-9204-d9712a2680a9', 'AICTE - Saksham Scholarship Scheme For Specially Abled Student (Technical Degree)', 'Education', 'Central', 'All India Council for Technical Education', 'Scholarship support for eligible students with disabilities pursuing a technical degree in an AICTE-approved institution.', 'Financial scholarship support as set out in the current scheme guidelines.', null, null, true, 'https://scholarships.gov.in/All-Scholarships', true),
  ('96f63eec-4b96-45ed-840b-cc3f6934c143', 'AICTE - Swanath Scholarship Scheme (Technical Degree)', 'Education', 'Central', 'All India Council for Technical Education', 'Scholarship support for students who meet the Swanath scheme conditions and are pursuing a technical degree in an AICTE-approved institution.', 'Financial scholarship support as set out in the current scheme guidelines.', null, null, false, 'https://scholarships.gov.in/All-Scholarships', true),
  ('b3d89e4c-e620-430a-aec9-91a347c97f3c', 'PM YASASVI Central Sector Scheme Of Top Class Education In College For OBC, EBC And DNT Students', 'Education', 'Central', 'Department of Social Justice and Empowerment', 'Top-class higher-education support for eligible OBC, EBC and DNT students admitted to institutions notified under PM YASASVI.', 'Education expenses and other support according to the current scheme guidelines and allocated slots.', null, null, false, 'https://scholarships.gov.in/All-Scholarships', true),
  ('a828faec-556f-47ee-9ead-1285e6b228de', 'Central Sector Scholarship Of Top Class Education For SC Students', 'Education', 'Central', 'Department of Social Justice and Empowerment', 'Financial support for eligible Scheduled Caste students pursuing higher education at institutions notified under the scheme.', 'Tuition and related educational support as specified by the current guidelines.', null, null, false, 'https://socialjustice.gov.in/schemes/27/archive', true),
  ('c34e06a8-c6ea-4d0e-aa12-a282d15adeb1', 'Post Matric Scholarship For Students With Disabilities', 'Education', 'Central', 'Department of Empowerment of Persons with Disabilities', 'Post-matric scholarship support for eligible students with benchmark disabilities continuing their education after Class 10.', 'Scholarship, allowances and fee support under the current scheme rules.', null, null, true, 'https://depwd.gov.in/en/scholarship-post-matric/', true),
  ('de39a67f-5d12-4b1d-afe7-d311693e4f26', 'Scholarship For Top Class Education For Students With Disabilities', 'Education', 'Central', 'Department of Empowerment of Persons with Disabilities', 'Higher-education scholarship support for eligible students with benchmark disabilities enrolled in institutions covered by the scheme.', 'Tuition and related support under the current scheme guidelines.', null, null, true, 'https://depwd.gov.in/en/scholarship/', true),
  ('a392f919-0928-4f93-ad34-a0b0e5dd53e9', 'PM-USP - Central Sector Scheme Of Scholarship For College And University Students (CSSS)', 'Education', 'Central', 'Department of Higher Education', 'Merit-based scholarship for eligible students pursuing college and university studies under PM-USP CSSS.', 'Annual scholarship support under the current scheme guidelines.', null, null, false, 'https://scholarships.gov.in/All-Scholarships', true),
  ('c6b48c32-135a-47c0-88ee-0e1dffebaa95', 'National Fellowship And Scholarship For Higher Education Of ST Students - Scholarship', 'Education', 'Central', 'Ministry of Tribal Affairs', 'Scholarship support for eligible Scheduled Tribe students pursuing higher education under the national scheme.', 'Higher-education scholarship support according to the current scheme guidelines.', null, null, false, 'https://scholarships.gov.in/All-Scholarships', true),
  ('c2d07050-cdd4-4c55-a0be-b56fd93dd3fc', 'Financial Assistance For Education To The Wards Of Beedi/Cine/IOMC/LSDM - Post Matric', 'Education', 'Central', 'Ministry of Labour and Employment', 'Education assistance for eligible post-matric students whose parent or guardian works in the specified Beedi, Cine, IOMC or LSDM industries.', 'Education assistance under the current scheme guidelines.', null, null, false, 'https://scholarships.gov.in/All-Scholarships', true),
  ('2e54dc41-1690-4a8a-9ccd-9c247ce5b3d1', 'Pradhan Mantri Kisan Samman Nidhi (PM-KISAN)', 'Agriculture', 'Central', 'Ministry of Agriculture and Farmers Welfare', 'Income-support scheme for eligible farmer families. Verify landholding and other conditions on the official PM-KISAN portal.', 'Direct income support as provided by the current scheme rules.', null, 'Farmer', false, 'https://pmkisan.gov.in/', true),
  ('b1b5913a-430b-4056-84a7-6a681f0bf6a8', 'Pradhan Mantri Awas Yojana - Urban 2.0 (PMAY-U 2.0)', 'Housing', 'Central', 'Ministry of Housing and Urban Affairs', 'Housing assistance for eligible urban families to construct, purchase or rent affordable housing through scheme-approved options.', 'Central assistance through the applicable PMAY-U 2.0 vertical and implementation partner.', null, null, false, 'https://pmaymis.gov.in/PMAYMIS2_2024/PMAY-urban-2.html', true),
  ('1d1ade13-1d34-4898-8e75-2bfaba9451ee', 'Ayushman Bharat - Pradhan Mantri Jan Arogya Yojana (PM-JAY)', 'Healthcare', 'Central', 'National Health Authority', 'Health assurance for eligible families for secondary and tertiary care at empanelled hospitals. Check beneficiary eligibility and current coverage on the official portal.', 'Cashless hospital treatment for eligible beneficiaries under current PM-JAY rules.', null, null, false, 'https://pmjay.gov.in/', true),
  ('f223ce5a-6299-46a1-ae07-638235facc0b', 'Pradhan Mantri Mudra Yojana (PMMY)', 'Business', 'Central', 'Department of Financial Services', 'Institutional credit scheme for eligible micro enterprises, delivered through participating lending institutions.', 'Business loans under the applicable PMMY categories; approval is subject to lender assessment.', null, 'Entrepreneur', false, 'https://financialservices.gov.in/pradhan-mantri-mudra-yojana-pmmy', true),
  ('2327ffcb-7f42-48ec-900f-65fd89311f94', 'Pradhan Mantri Ujjwala Yojana (PMUY)', 'Women', 'Central', 'Ministry of Petroleum and Natural Gas', 'LPG connection scheme for eligible adult women from households meeting the current PMUY criteria.', 'Eligible households can receive connection support and applicable scheme benefits.', 'Female', null, false, 'https://www.pmuy.gov.in/index.aspx', true),
  ('c51656c4-4d72-488c-9bd0-85c7b862ec03', 'Sukanya Samriddhi Account Scheme', 'Women', 'Central', 'Ministry of Finance - National Savings Institute', 'Government-backed savings account that a guardian can open for an eligible girl child through a post office or participating bank.', 'Long-term savings with interest at the rate notified by the Government from time to time.', 'Female', null, false, 'https://www.nsiindia.gov.in/InternalPage.aspx?Id_Pk=150', true),
  ('abd74ffe-dfc1-4d9a-b49f-31979c6f812c', 'Pradhan Mantri Street Vendor AtmaNirbhar Nidhi (PM SVANidhi)', 'Employment', 'Central', 'Ministry of Housing and Urban Affairs', 'Working-capital support for eligible street vendors through the PM SVANidhi scheme.', 'Loan tranches and other incentives under current rules, subject to lender and scheme conditions.', null, 'Street vendor', false, 'https://pmsvanidhi.mohua.gov.in/', true),
  ('d9645ada-c159-4bde-a2ea-859be28ddf08', 'Stand-Up India', 'Business', 'Central', 'Department of Financial Services', 'Bank credit support to eligible SC/ST and women entrepreneurs for greenfield enterprises.', 'Composite bank loan support subject to current scheme and lending criteria.', null, 'Entrepreneur', false, 'https://www.standupmitra.in/', true),
  ('349e99d5-ddae-4e3d-b6d8-6f363b5d987f', 'National Means-cum-Merit Scholarship Scheme (NMMSS)', 'Education', 'Central', 'Department of School Education and Literacy', 'Merit-based scholarship for eligible students continuing secondary education, subject to current scheme criteria.', 'Scholarship assistance under the current NMMSS guidelines.', null, null, false, 'https://scholarships.gov.in/All-Scholarships', true),
  ('018e34f1-4681-47a6-8e82-3ebe2a596e9d', 'National Overseas Scholarship', 'Education', 'Central', 'Department of Social Justice and Empowerment', 'Overseas higher-education support for eligible candidates from communities covered by the National Overseas Scholarship.', 'Financial assistance for approved overseas higher studies under current scheme guidelines.', null, null, false, 'https://nosmsje.gov.in/', true)
on conflict (id) do update set
  scheme_name = excluded.scheme_name,
  category = excluded.category,
  level = excluded.level,
  ministry = excluded.ministry,
  description = excluded.description,
  benefits = excluded.benefits,
  gender = excluded.gender,
  occupation = excluded.occupation,
  disability_required = excluded.disability_required,
  official_url = excluded.official_url,
  is_published = excluded.is_published,
  updated_at = now();
